name: gh-describe
description: "Emulate `git describe --tags` for shallow clone repositories."
author: Proudust

inputs:
  token:
    description: Personal Access Token (PAT)
    default: ${{ github.token }}
  repo:
    description: Target repository
    default: ${{ github.repository }}
  commit-ish:
    description: >
      Commit-ish object names to describe.
      The branch or tag ref that triggered the workflow run.
    default: ${{ github.ref }}
  match:
    description: Only consider tags matching the given glob pattern.
    default: ""
  exclude:
    description: Do not consider tags matching the given glob pattern.
    default: ""
  default:
    description: If the name is not found, use this value.
    default: ""

outputs:
  describe:
    description: >
      `git describe --tags`-like description.
      ex) v1.0.4-14-g2414721
  tag:
    description: >
      The most recent tag.
      ex) v1.0.4
  distance:
    description: >
      The number of additional commits from the most recent tag.
      ex) 14
  sha:
    description: >
      The object name for the commit itself.
      ex) 2414721
  short-sha:
    description: >
      The object name for the commit itself.
      ex) 2414721

runs:
  using: node20
  main: dist/actions.js

branding:
  icon: tag
  color: gray-dark
